version: '3.8'
services:
  ethnode-sidecar:
    image: node:19.2.0
    container_name: ethnode-sidecar
    working_dir: /app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules:delegated
    ports:
      - ${NEST_LOCAL_PORT}:3000
      - ${NEST_LOCAL_DEBUG_PORT}:9229
    command: sh -c "npm run start:debug"
